<?php

namespace Store\MobilePhone\Model\ResourceModel;

class Category extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    protected function _construct()
    {
        $this->_init('category', 'category_id');
    }

    public function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        $image = $object->getData('image');
        if ($image != null) {
            $imageUploader = \Magento\Framework\App\ObjectManager::getInstance()->get('Store\MobilePhone\CategoryImageUpload');
            $imageUploader->moveFileFromTmp($image);
        }
        return $this; // TODO: Change the autogenerated stub
    }
}

