<?php

namespace Dev\Banner\Model;

use Dev\Banner\Api\Data\BannerInterface;
use Magento\Framework\Model\AbstractModel;

class Banner extends AbstractModel implements BannerInterface
{
    const STATUS_ENABLED = 1;
    const STATUS_DISABLED = 0;
    const BANNER_ID = 'banner_id';
    const NAME = 'name';
    const DESCRIPTION = 'description';
    const IMAGE = 'image';
    const STATUS = 'status';


    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init(\Dev\Banner\Model\ResourceModel\Banner::class);
    }

    public function getBannerId()
    {
        // TODO: Implement getBannerId() method.
        return $this->getData(self::BANNER_ID);
    }

    public function setBannerId($entityId)
    {
        // TODO: Implement setBannerId() method.
        $this->setData(self::BANNER_ID, $entityId);
        return $this;
    }

    public function getName()
    {
        // TODO: Implement getName() method.
        return $this->getData(self::NAME);
    }

    public function setName($name)
    {
        // TODO: Implement setName() method.
        $this->setData(self::NAME, $name);
        return $this;
    }

    public function getDescription()
    {
        // TODO: Implement getDescription() method.
        return $this->getData(self::DESCRIPTION);
    }

    public function setDescription($description)
    {
        // TODO: Implement setDescription() method.
        $this->setData(self::DESCRIPTION, $description);
        return $this;
    }

    public function getImage()
    {
        // TODO: Implement getImage() method.
        return $this->getData(self::IMAGE);
    }

    public function setImage($image)
    {
        // TODO: Implement setImage() method.
        $this->setData(self::IMAGE, $image);
        return $this;
    }

    public function getStatus()
    {
        // TODO: Implement getStatus() method.
        return $this->getData(self::STATUS);
    }

    public function setStatus($status)
    {
        // TODO: Implement setStatus() method.
        $this->setData(self::STATUS, $status);
        return $this;
    }
}
